name: Lint Code Base
on:
  pull_request: # 对 PR 进行检查
    branches: [ main,beta ]
  workflow_dispatch:
    inputs:
      reason:
        description: '手动运行的原因 (Reason for manual run)'
        required: false
        default: '常规代码格式测试 (Regular Lint Code test)'

jobs:
  lint-and-check:
    name: Run Style and Correctness Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
      actions: write
      pull-requests: read

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 检查是否仅修改文档
      - name: Check for non-documentation file changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files_ignore: |
            **.md
            docs/**
            LICENSE
            .gitignore
            .github/**
            app/build.gradle.kts

      # 设置 JDK 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          java-version: '17'
          distribution: 'temurin'

      # 设置 Gradle 环境
      - name: Setup Gradle
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: gradle/actions/setup-gradle@v3

      # 设置执行权限
      - name: Grant execute permission for gradlew
        if: steps.changed-files.outputs.any_changed == 'true'
        run: chmod +x ./gradlew

      # ktlint 风格检查
      - name: Run ktlint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ./gradlew ktlintCheck

      # Android Lint 检查
      - name: Run Android Lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ./gradlew lintDebug

      # 单元测试检查
      - name: Run Android Unit Testing
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ./gradlew app:testDebugUnitTest

